spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: 123
        url: jdbc:postgresql://localhost:5432/university
        username: manager
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL82Dialect
    mvc:
        hiddenmethod:
            filter:
                enabled: true

    profiles:
        active: default
